= Confluent Hybrid Cloud (Azure) Demo
:doctype: article
:icon: font
:cloudprovider: Azure
:resourcepath: resources
:externalip: localhost

v0.9, May 18th, 2020

== Introduction
Hybrid Cloud and Multi Cloud are a reality in modern IT architectures.
Some reasons include:

* existing applications running in data-centers on premise
* legacy technologies still widely used (Mainframes) but a need to liberate the data
* many companies require to have an Hybrid and Multi-Cloud architecture to avoid vendor lock-in.
* some processing should happen on premise, while replicating the whole data or only the result of the process to the cloud for * etc, etc

How can you make sure you handle all the challenges above without complicating your architecture with multiple different solutions and data integration processes?
Confluent Platform can be the lingua franca that lets all these different infrastructures talk to each other, offering an the same APIs independently of the underlying architecture.

[quote]
____

In this demo we'll guide you in a data journey, starting from Data generated on premise in a traditional database, collecting CDC events on premise and then bridge this data to Confluent Cloud on {cloudprovider}. We'll then use KSQL to manipulate and enrich the data. Connectors are use to both sink existing data and source data natively created in the cloud eco-systems to enrich the data already in Confluent Cloud. In the end new valuable data will arrive back to the on Premise to make sure even legacy applications can reap the benefits of the cloud eco-systems. 

The possibilities are almost endless!

ksqlDB is the streaming engine for Apache Kafka using a sql-like lanaugage making it easy for non-developers and developers alike to quickly develop powerful streaming applications.


____


== Demo Access

Open Control Center link:http://{externalip}:9021[here, window=_blank]
